# Generated by Django 5.0.6 on 2024-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0003_alter_crew_journeys_alter_journey_route_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"verbose_name_plural": "routes"},
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["name"], "verbose_name_plural": "stations"},
        ),
        migrations.AlterModelOptions(
            name="traintype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cargo",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="traintype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["source", "destination"], name="train_route_source__10e67e_idx"
            ),
        ),
    ]
