# Generated by Django 5.0.6 on 2024-06-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0004_alter_journey_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to="train_routes.train",
            ),
        ),
    ]
