# Generated by Django 5.0.6 on 2024-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0005_alter_journey_train"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="cargo",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(),
        ),
    ]
