# Generated by Django 5.0.6 on 2024-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0006_alter_ticket_cargo_alter_ticket_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(unique=True),
        ),
    ]
