# Generated by Django 5.0.6 on 2024-06-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0007_alter_ticket_seat"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("journey", "seat")},
        ),
    ]
