# Generated by Django 5.0.6 on 2024-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0008_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]
