# Generated by Django 5.0.6 on 2024-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0009_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("journey", "seat")},
        ),
    ]
