# Generated by Django 5.0.6 on 2024-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0010_alter_ticket_seat_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
