# Generated by Django 5.0.6 on 2024-06-06 19:54

import train_routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_routes", "0011_train_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_routes.models.image_file_path
            ),
        ),
    ]
