# Generated by Django 5.0.6 on 2024-06-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_routes', '0013_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
